# Generated by Django 4.2.10 on 2024-02-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historicalModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('community', models.CharField(max_length=255)),
                ('contruction_yr', models.IntegerField()),
                ('typology', models.CharField(max_length=255)),
                ('orig_use_ty', models.CharField(max_length=255)),
                ('architect', models.CharField(blank=True, default='', max_length=255)),
                ('architecture_style', models.CharField(blank=True, default='', max_length=255)),
                ('development_era', models.CharField(blank=True, default='', max_length=255)),
                ('significance_summ', models.CharField(blank=True, default='', max_length=255)),
                ('integrity_stmt', models.CharField(blank=True, default='', max_length=255)),
                ('pic_url', models.URLField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zodiac', models.CharField(choices=[('1', 'Aries'), ('2', 'Taurus'), ('3', 'Gemini'), ('4', 'Cancer'), ('5', 'Leo'), ('6', 'Virgo'), ('7', 'Libra'), ('8', 'Scorpio'), ('9', 'Sagittarius'), ('10', 'Capricorn'), ('11', 'Aquarius'), ('12', 'Pisces')], max_length=2)),
                ('horror', models.CharField(choices=[('1', 'Cemetery'), ('2', 'Warehouse'), ('3', 'Hospital'), ('4', 'Factory'), ('5', 'Hotel'), ('6', 'Grocery Store'), ('7', 'None')], max_length=1)),
                ('bridges', models.BooleanField(default=False)),
                ('profession', models.CharField(choices=[('1', 'Baker'), ('2', 'Civil Engineer'), ('3', 'Farmer'), ('4', 'Priest'), ('5', 'Librarian'), ('6', 'Teacher'), ('7', 'None')], max_length=1)),
            ],
        ),
    ]
