# Generated by Django 4.2.10 on 2024-02-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='horror',
            field=models.CharField(choices=[('Cemetery', 'Cemetery'), ('Warehouse', 'Warehouse'), ('Hospital', 'Hospital'), ('Factory', 'Factory'), ('Hotel', 'Hotel'), ('Grocery Store', 'Grocery Store'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='profession',
            field=models.CharField(choices=[('Baker', 'Baker'), ('Civil Engineer', 'Civil Engineer'), ('Farmer', 'Farmer'), ('Priest', 'Priest'), ('Librarian', 'Librarian'), ('Teacher', 'Teacher'), ('None', 'None')], max_length=20),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='zodiac',
            field=models.CharField(choices=[('Aries', 'Aries'), ('Taurus', 'Taurus'), ('Gemini', 'Gemini'), ('Cancer', 'Cancer'), ('Leo', 'Leo'), ('Virgo', 'Virgo'), ('Libra', 'Libra'), ('Scorpio', 'Scorpio'), ('Sagittarius', 'Sagittarius'), ('Capricorn', 'Capricorn'), ('Aquarius', 'Aquarius'), ('Pisces', 'Pisces')], max_length=20),
        ),
    ]
